### ISSUE TITLE
stmb* call get_ra with carry set

### ISSUE THREAD

**Issue by peterferrie** [AcheronVM/acheronvm#11]
OP stmb, ra, mem, "memory(rA) byte := rP."
 sec
OP stm, ra, mem, "memory(rA) := rP."
 lda #0
...
:sta zptemp
 php   ; save the carry flag for post-get_ra
 get_ra

there needs to be a clc between the php and the get_ra, which increases the cycle count even further.

**Comment by peterferrie** [comment]
Same issue with ldmb*, but calling get_rd instead.

**Comment by AcheronVM** [comment]
Yes, good catch.  The memory operations are going through some rewrites at the moment as well, but I did fix these combined versions for the interim, even though as per the comments I'm not that happy with them. ;)
