### ISSUE TITLE
alternative ldmr

### ISSUE THREAD

**Issue by peterferrie** [AcheronVM/acheronvm#13]
this part:

 ldy #0
 lda (zptemp),y
 ; Store into the new rP
...
 bcc :+
  ; Byte version
  sty 1,x ; clear the high byte
  bcs :++
  ; Word version
: iny
  lda (zptemp),y
  sta 1,x 
:jmp mainLoopRestoreY

can avoid a branch

 ldy #0
 lda (zptemp),y
 ; Store into the new rP
...
 bcs :+  ; Byte version
  ; Word version
  iny
  lda (zptemp),y
  tay
: sty 1,x 
:jmp mainLoopRestoreY

which will save some bytes and cycles, too.

**Comment by AcheronVM** [comment]
Good call.  Integrated.
