### ISSUE TITLE
alternative bswap

### ISSUE THREAD

**Issue by peterferrie** [AcheronVM/acheronvm#14]
replace

 dey
 save_y
 ldy 0,x
 lda 1,x
 sta 0,x
 sty 1,x
 jmp mainLoopRestoreY

with

 lda 0,x
 pha
 lda 1,x
 sta 0,x
 pla
 sta 1,x
 jmp mainLoop0

saves a byte and some cycles.

**Comment by AcheronVM** [comment]
Thanks, integrated.
