### ISSUE TITLE
addea2 doesn't double rA properly?

### ISSUE THREAD

**Issue by peterferrie** [AcheronVM/acheronvm#15]
lda 0,y
 asl
 bcc :+
  inc 1,x
  clc
:adc 0,x
 sta 0,x
 lda 1,y
 adc 1,x
 sta 1,x

1,y is not doubled, only 0,y is.
It looks like it should be

 lda 0,y
 asl
 sta zptemp
 lda 1,y
 rol
 tay
 lda zptemp
 clc
 adc 0,x
 sta 0,x
 tya
 adc 1,x
 sta 1,x

**Comment by AcheronVM** [comment]
Fixed. I had only been using it with small offset and missed that.

I really appreciate your bugfixes and attention to detail in the code.  While the prior 2012 incarnation had a good amount of application code using it, this released version hasn't hit that point yet and is being written a bit blind, retaining some code from the older models that ended up half-converted.  These eyeballs of open source are a tremendous help as I'm spinning plates elsewhere.
