### ISSUE TITLE
Typos in andr?

### ISSUE THREAD

**Issue by JohnMBrooks** [AcheronVM/acheronvm#2]
OP andr, ra, bits, "rP := rP & rA"
 get_ra_y
 lda 0,x
 and 0,y
 sta 0,x
 lda 1,x
 and 0,y
 sta 0,x
 jmp mainLoopRestoreY

Looks like it should be:

OP andr, ra, bits, "rP := rP & rA"
 get_ra_y
 lda 0,x
 and 0,y
 sta 0,x
 lda 1,x
 and 1,y
 sta 1,x
 jmp mainLoopRestoreY

**Comment by AcheronVM** [comment]
Fixed.  I know I've fixed this before, but I've combined a few versions together and this probably fell through the cracks.
