### ISSUE TITLE
alternative signx

### ISSUE THREAD

**Issue by peterferrie** [AcheronVM/acheronvm#5]
replace

 lda 0,x
 bpl :+
 lda #$ff
 bmi :++
:lda #0
:sta 1,x

with 

 lda 0,x
 eor #$80
 asl
 lda #$ff
 adc #0
 sta 1,x

is one byte smaller but three or one cycles slower, depending on which path the original took.

**Comment by KarolS** [comment]
What about 

lda 0,x
ora #$7f
bmi :+
lda #0
: sta 1,x

or 

lda 0,x
and #$80
bpl :+
lda #$ff
: sta 1,x

from https://wiki.nesdev.com/w/index.php/Synthetic_instructions#Sign-extend

The original variant takes (ignoring the initial load and store) 8 bytes and 5/7 cycles, the EOR variant takes 7 bytes and 8 cycles, the two ones from nesdev.com take 6 bytes and 5/6 cycles.

**Comment by AcheronVM** [comment]
Excellent find, both smaller and faster.

Most of the algos I've seen and fiddled with used an extra register, e.g. LDX #0 and DEX if it was negative.  With such small instruction implementations, it's good to see it all contained in .A, as the saving/restoring of .X or .Y would have been a relatively significant burden.

Committing with this.

**Comment by barrym95838** [comment]
Hi!  Sorry I'm a few days late to the party, but have you considered trying the "reverse compare" technique?

```
OP signx, none, bits, "Sign extend an 8-bit value in rP into 16 bits."
  lda  #$7f
  cmp  0,x    ; clear carry if negative
  sbc  #$7f
  sta  1,x    ; $00 for +, $ff for -
  jmp  mainLoop0
```
(This is my first post on GitHub, so I'm still very green ...)
Mike B.
