### ISSUE TITLE
alternative roll

### ISSUE THREAD

**Issue by peterferrie** [AcheronVM/acheronvm#6]
replace

 lda 1,x
: cmp #$80
  rol 0,x
  rol
  dey
 bne :-
 sta 1,x

with

: asl 1,x
  rol 0,x
  bcc :+ 
  inc 1,x
: dey 
  bne :--

is one byte smaller but many times slower.

**Comment by AcheronVM** [comment]
The optimization criteria are for fast and small and powerful, so even if something has a slight gain in size, a hefty loss in speed would make an overall regression.  Likewise, if something is a bit faster, but much larger, that would also be considered a regression.  It's certainly a balancing act, but for now I'll keep it as is.
