### ISSUE TITLE
caser missing bne target

### ISSUE THREAD

**Issue by peterferrie** [AcheronVM/acheronvm#8]
" bne :-   ;; TODO - where is this supposed to go?"

It looks like it should be a "bne :+" to a ":ldy iptr_offset/jmp mainLoop0" (or just "jmp mainLoopRestoreY") which needs to be added.

**Comment by AcheronVM** [comment]
Yeah, a shared exit point probably existed above it, but got lost to the sands of time.  I rewrote the case tests to use EOR to avoid carry effects, and to use .Y before .X so it can be restored early.
