### ISSUE TITLE
alternative jump

### ISSUE THREAD

**Issue by peterferrie** [AcheronVM/acheronvm#9]
replace

 lda (iptr),y
 sta zptemp
 iny
 lda (iptr),y
 sta iptr+1
 lda zptemp
 sta iptr

with

 lda (iptr),y
 tax
 iny
 lda (iptr),y
 sta iptr+1
 stx iptr
 ldx pptr

to save one byte and one cycle.

**Comment by AcheronVM** [comment]
This would need to perform a `stx pptr` first in order to work.  .X freely changes its value without updating `pptr`.  Only when we leave Acheron code must `pptr` be updated.
